// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Order struct {
	ID        uuid.UUID
	UserID    sql.NullString
	ItemID    uuid.NullUUID
	Quantity  int32
	CreatedAt time.Time
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
