// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Price       int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Order struct {
	ID        pgtype.UUID
	UserID    pgtype.Text
	ItemID    pgtype.UUID
	Quantity  int32
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
